### ISSUE TITLE
Race condition when calling DeferCleanup from concurrent goroutines

### ISSUE THREAD

**Issue by onsi** [onsi/ginkgo#1204]
cc @meln5674

**Comment by fischerman** [comment]
Was this fixed in https://github.com/onsi/ginkgo/commit/07fc3a0?

I'm currently seeing the following when I do `go test -race ...`
```
runtime: bad pointer in frame ....glob..func1.4 at 0xc000235ec0: 0x10
fatal error: invalid pointer found on stack
```
Could this be related?

**Comment by onsi** [comment]
yup this should have been fixed.  are you running `go test -race` against ginkgo or your own test suite?

**Comment by fischerman** [comment]
I'm running my own test suite. It's weird... With -race flat set I would have expected a "race detected" message. But maybe it breaks trying to generate this message? 

I wasn't able to set up a minimal example but it looks something like this:
```go
FIt("foo", func() {
	a := &someStruct{...}
	b, err := bar(a)     // bar returns err!=nil
	Expect(err).NotTo(HaveOccurred())
	Expect(b.c).To(PointTo(ConsistOf(haveX("hello"))))
})

func haveX(name string) types.GomegaMatcher {
	return WithTransform(func(c _) *string { return c.d }, PointTo(Equal(name)))
}
```
No before, after, or defer. `bar` doesn't use Go routines or channels. Really no concurrency at all in the code under test. It basically just turns a into b. However, both a and b contain pointers.

When I remove the second assertion I do get the intended result "[FAILED] Unexpected error...":
```go
FIt("foo", func() {
	a := &someStruct{...}
	b, err := bar(a)     // bar returns err!=nil
	Expect(err).NotTo(HaveOccurred())
	// Expect(b.c).To(PointTo(ConsistOf(haveX("hello"))))
})

func haveX(name string) types.GomegaMatcher {
	return WithTransform(func(c _) *string { return c.d }, PointTo(Equal(name)))
}
```

Since, in either case, the error assertion should panic, how can an assertion after it cause a memory corruption (only when race detection is enabled). If you have any idea let me know. 

```
go 1.21.1 linux/amd64
github.com/onsi/ginkgo/v2 v2.13.0
github.com/onsi/gomega v1.27.10
```

**Comment by onsi** [comment]
**faaaascinating** - i'll have to poke around and see if I can reproduce it.  Are you, by any chance, using `cgo` or `unsafe`?  Should I expect to reproduce it if I follow your example - or are you saying that it doesn't actually reproduce it but that the relevant code kinda looks like it.

If the latter - can you share the code?  If not, that's fine - but can you maybe share if there's anything that isn't vanilla-go about the code?  (e.g. it uses cgo or unsafe or some third-party library).

**Comment by onsi** [comment]
🤯  super quick update.  I clone the repo and ran it locally (I still happen to be on go 1.20) and all worked well.  I ran it in docker with 1.21.1 (thanks for that one-liner by the way) and saw your issue.

Then I change the go version to 1.20 in the go.mod  and ran:

docker run --rm -v $(pwd):/work --workdir /work golang:1.20 go test -race .

**AND IT WORKED**

So this seems to be an issue introduced in 1.21 (I checked that 1.20.10 is fine and 1.21.0 is not).  The release notes don't explicitly mention changes to the race detector and I tried perusing the 1.20 => 1.21 diff and... quickly gave up!

You have such a simple reproducer, I'd suggest opening and issue on golang.

**Comment by fischerman** [comment]
Thanks for looking into it. I've reported the issue upstream: https://github.com/golang/go/issues/63657

**Comment by fischerman** [comment]
The issue has been confirmed. I think you can close this one.

Thanks again for your help!

**Comment by onsi** [comment]
nice - thanks for the update :)
